### ISSUE TITLE
Sample Image Classification Script for Backend

### ISSUE THREAD

**Issue by smaranjitghose** [sanscript-tech/womens_safety-java#12]
Create a script say ```awesome_classifier.py``` that reads an image, processes it, loads a PyTorch model and gives us inference. You can use any demo models for this

**Comment by khushboogupta13** [comment]
Can I work on this?

**Comment by simanfathima** [comment]
Hello can I work on this too?

**Comment by jyotijauhari** [comment]
@khushboogupta13 @simanfathima  any update?
