### ISSUE TITLE
Create a CONTRIBUTING.md

### ISSUE THREAD

**Issue by muddhit** [sanscript-tech/womens_safety-java#2]
Create a CONTRIBUTING.md mentioning all the guidelines mentioned on the slack channel. Mention proper instructions and guidelines to follow right from forking the repo to submitting a PR.

**Comment by muddhit** [comment]
Can i work on this issue

**Comment by jyotijauhari** [comment]
@Mukulbaid63 contribution guidelines  is already mentioned in [how to start](https://github.com/sanscript-tech/womens_safety-java#how-to-start--) section. 

But confirm once from @smaranjitghose if separate file named contribution.md is needed or not.

**Comment by smaranjitghose** [comment]
> @Mukulbaid63 contribution guidelines is already mentioned in [how to start](https://github.com/sanscript-tech/womens_safety-java#how-to-start--) section.
> 
> But confirm once from @smaranjitghose if a separate file named contribution.md is needed or not.

Instructions specific for PRs are already there in the README and if required we would make it more elaborate. As of now, we do not require a separate file for it. Currently, our main focus is on the code base forming the heart of the app
