### ISSUE TITLE
App Base Code

### ISSUE THREAD

**Issue by smaranjitghose** [sanscript-tech/womens_safety-java#4]
# Main Idea
A basic Flutter App with a Splash Screen that displays "Bhavti Abhay" instead of Hello World on opening.
# Suggestions:
- Put the code in a directory bhavti_abhay and push that to the root level of master directory
- Please attach a small clip in your PR's description regarding the app's working in the simulator 
- Try to use this  color palette for mockups:
![Equality Color Palette - color-hex com](https://user-images.githubusercontent.com/46641503/96466088-5bf9af00-1247-11eb-9195-e94fb23da912.png)
- For now, go with Montserrat Font
- Do not generate a build apk

**Comment by HaripriyaB** [comment]
I would like to take this up. Pls assign me

**Comment by HaripriyaB** [comment]
I have a doubt to be clarified. The project name says it's a java project but this issue suggests to make a flutter app. So which one is going to be implemented? @smaranjitghose

**Comment by smaranjitghose** [comment]
> I have a doubt to be clarified. The project name says it's a java project but this issue suggests to make a flutter app. So which one is going to be implemented? @smaranjitghose

We are going ahead with Java
