### ISSUE TITLE
Custom Splash Screen for the App

### ISSUE THREAD

**Issue by smaranjitghose** [sanscript-tech/womens_safety-java#5]
# Rough Idea:
You are welcome to experiment with animations but the animated figure of a women and a shield might be good to suit the theme

**Comment by saloniankita** [comment]
Can I work on this issue @smaranjitghose ?
Kindly assign me.

**Comment by saloniankita** [comment]
Can we try it with some other animations/illustrations @smaranjitghose ?

**Comment by jyotijauhari** [comment]
@saloniankita , yes the last pr contains just a sample splash screen. You can improve it by adding some other animations. But make sure it should be according to rough idea mentioned by @smaranjitghose in description.

Cc : @smaranjitghose

**Comment by jyotijauhari** [comment]
@saloniankita try to complete this issue in this week itself

**Comment by saloniankita** [comment]
Sure @JyotiJauhari
