### ISSUE TITLE
Firebase Integration for the App

### ISSUE THREAD

**Issue by smaranjitghose** [sanscript-tech/womens_safety-java#6]
For now, we simply require to Log in with Google, Facebook options. Create a dummy project and push the API key, we can later shift it once we pass the beta stage

**Comment by rashmitha520** [comment]
Can i work on it?

**Comment by kritikashah20** [comment]
Can I also work on it?

**Comment by jyotijauhari** [comment]
@kritikashah20 any update?

**Comment by kritikashah20** [comment]
yes mam, I have created a dummy project and integrated the login features as well. I have a query regarding API key, which I asked to Project leaders.
