### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by smaranjitghose** [sanscript-tech/womens_safety-java#7]
# Core Idea:

Simplistic Design similar to what we have for WhatsApp like Profile Picture, Contact no, Email, Emergency No, Name

**Comment by Bijay555** [comment]
Can you assign this to me

**Comment by shatabdi764** [comment]
Can I work on this too? I would like to make a profile page for Women's Safety.

**Comment by smaranjitghose** [comment]
> Can I work on this too? I would like to make a profile page for Women's Safety.

Sure. Colab with @Bijay555 on this

**Comment by jyotijauhari** [comment]
@Bijay555 @shanawas1112 please do this in this week only. Otherwise you will be unassigned.

**Comment by shanawas1112** [comment]
I want bijay contact number

**Comment by smaranjitghose** [comment]
> I want bijay contact number

Please make use of slack

**Comment by Bijay555** [comment]
@smaranjitghose look at the draft PR and tell me if there is anything to add.
